#!/usr/bin/env python3
"""Regenerate graphify-out.md: a single-file map of this codebase's structure.

Walks the repo, and for every .py file lists its top-level classes/functions
(and methods) with signatures, via the stdlib `ast` module — no parsing
dependency needed. Non-Python files are listed with line counts only.

Usage: python scripts/graphify.py
Re-run any time the structure changes; it fully overwrites graphify-out.md.
"""
from __future__ import annotations

import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "graphify-out.md"
SKIP_DIRS = {".git", "__pycache__", "node_modules", "venv", ".venv", ".claude"}


def sig(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = [a.arg for a in node.args.args]
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    return f"{prefix} {node.name}({', '.join(args)})"


def py_structure(path: pathlib.Path) -> list[str]:
    lines = []
    try:
        tree = ast.parse(path.read_text())
    except SyntaxError as e:
        return [f"  ⚠ unparsable: {e}"]
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            lines.append(f"- `{sig(node)}`")
        elif isinstance(node, ast.ClassDef):
            lines.append(f"- `class {node.name}`")
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    lines.append(f"  - `{sig(sub)}`")
    return lines or ["  (no top-level classes/functions)"]


def main() -> None:
    files = sorted(
        p for p in ROOT.rglob("*")
        if p.is_file()
        and not any(part in SKIP_DIRS or part.startswith(".") for part in p.relative_to(ROOT).parts)
        and p.name != OUT.name
    )

    out = ["# Codebase Map", "", "Auto-generated by `scripts/graphify.py` — do not edit by hand. Re-run after structural changes.", ""]
    for path in files:
        rel = path.relative_to(ROOT)
        if path.suffix == ".py":
            out.append("")
            out.append(f"## {rel}")
            out.extend(py_structure(path))
            out.append("")
        else:
            n = sum(1 for _ in path.open("rb")) if path.stat().st_size else 0
            out.append(f"- `{rel}` ({n} lines)")

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
